apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: http-echo
spec:
  project: vntechies
  destination:
    server: https://1470FBE09E07236EE4CF9E9295AE3126.gr7.ap-southeast-1.eks.amazonaws.com
    namespace: http-echo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/hungran/http-echo-helm-chart.git
    path: charts/http-echo
    targetRevision: "http-echo-0.1.7"
    helm: 
      values: |
        #
        # IMPORTANT NOTE
        #
        # This chart inherits from the http-echo common library chart. You can check
        # the default values/options here:
        #   https://github.com/hungran/chart-repo-template
        #

        image:
          repository: hashicorp/http-echo
          pullPolicy: IfNotPresent
          # Overrides the image tag whose default is the chart appVersion.
          # tag: "0.2.3"
        arguments: ['--text', 'hello from VietAWS - Demo AWS CloudDay - Thank you for listening']

        # This is a simple echo service so we always harden.
        securityContext:
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000

        ingress:
          enabled: true
          className: nginx
          annotations:
            # kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
            nginx.ingress.kubernetes.io/service-upstream: "true"
          hosts:
            - host: http-echo.hungran.cloud
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: http-echo-hungran-cloud-tls-secret
              hosts:
                - http-echo.hungran.cloud
        autoscaling:
          enabled: true
          minReplicas: 2
          maxReplicas: 6
          targetCPUUtilizationPercentage: 80

